# Generated by Django 4.2.7 on 2023-11-29 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('salary', models.CharField(max_length=120)),
                ('department', models.CharField(max_length=120)),
            ],
        ),
    ]
